import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('final_output_cleaned.csv')
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d')
df['Month'] = df['Date'].dt.to_period('M')
sns.set(style="whitegrid")
monthly_sales = df.groupby('Month')['Revenue'].sum().reset_index()
region_sales = df.groupby('Region')['Revenue'].sum().reset_index()
category_sales = df.groupby('Category')['Revenue'].sum().reset_index()
fig, axs = plt.subplots(3, 1, figsize=(10, 15))
sns.lineplot(ax=axs[0], x=monthly_sales['Month'].astype(str), y='Revenue', data=monthly_sales, marker='o')
axs[0].set_title("Monthly Revenue Trend")
axs[0].set_xlabel("Month")
axs[0].set_ylabel("Total Revenue")
axs[0].tick_params(axis='x', rotation=45)
sns.barplot(ax=axs[1], x='Region', y='Revenue', data=region_sales, palette="Blues_d")
axs[1].set_title("Region-wise Revenue")
axs[1].set_xlabel("Region")
axs[1].set_ylabel("Revenue")
sns.barplot(ax=axs[2], x='Category', y='Revenue', data=category_sales, palette="Oranges_d")
axs[2].set_title("Category-wise Revenue")
axs[2].set_xlabel("Category")
axs[2].set_ylabel("Revenue")
plt.tight_layout()
plt.show()
fig.savefig("dashboard.png", dpi=300)
