
import pandas as pd
import json
import matplotlib.pyplot as plt
sales_df = pd.read_csv('sales_data.csv')
sales_df['Date'] = pd.to_datetime(sales_df['Date'], format='%d-%m-%Y')
with open('product_metadata.json') as f:
    product_data = json.load(f)
product_df = pd.DataFrame(product_data)
region_df = pd.read_excel('region_info.xlsx')
merged_df = pd.merge(sales_df, product_df, on='Product', how='left')
final_df = pd.merge(merged_df, region_df, on='Region', how='left')
print("Final Merged Data Preview:")
print(final_df.head())
print("\n Column Data Types:")
print(final_df.dtypes)
final_df['Month'] = final_df['Date'].dt.to_period('M')
monthly_sales = final_df.groupby('Month')['Revenue'].sum().reset_index()
plt.figure(figsize=(8, 5))
plt.plot(monthly_sales['Month'].astype(str), monthly_sales['Revenue'], marker='o')
plt.title(" Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Total Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
region_sales = final_df.groupby('Region')['Revenue'].sum().reset_index()
plt.figure(figsize=(6, 4))
plt.bar(region_sales['Region'], region_sales['Revenue'], color='skyblue')
plt.title(" Region-wise Revenue")
plt.xlabel("Region")
plt.ylabel("Revenue")
plt.tight_layout()
plt.show()
category_sales = final_df.groupby('Category')['Revenue'].sum().reset_index()
plt.figure(figsize=(6, 4))
plt.bar(category_sales['Category'], category_sales['Revenue'], color='orange')
plt.title(" Category-wise Revenue")
plt.xlabel("Category")
plt.ylabel("Revenue")
plt.tight_layout()
plt.show()
summary = final_df.groupby(['Region', 'Category'])['Revenue'].sum().reset_index()
print("\n Revenue by Region and Category:")
print(summary)
